version: "3"
services:
  mysqldb:
    image: mysql:5.7
    restart: always
    container_name: mysql57
    ports:
      - 3306:3306
    volumes:
      - /var/vol_dockers/mysqldb/conf:/etc/mysql/conf.d
      - /var/vol_dockers/mysqldb/data:/var/lib/mysql
    environment:
      MYSQL_PSAAWORD: 123456
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: root
      MYSQL_DATABASE: database